swagger: "2.0"
info:
  description: "HTMLAnalizeApi"
  version: "0.1.0"
  title: "HTMLAnalizeApi"
host: "6hri9bwr0j.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/production"
schemes:
- "https"
paths:
  /analize:
    get:
      summary: "websiteの情報を解析して表示するAPI"
      description: "website内で使われている画像などのAssetのURLや住所、電話番号などの情報を抽出して返してくれるAPIです"
      produces:
      - "application/json"
      parameters:
      - name: "url"
        in: "query"
        description: "websiteのURL"
        required: true
      responses:
        200:
          description: "successful"
          schema:
            type: "object"
